// dashboard/lib/trading-agent-hq/mockState.ts
// TradingAgentHQ — THQ-4 static mock ViewModel.
// HONEST mock: reflects real M-0Z-6 posture (paper LIVE, closedCycles=0 DATA_GAP, M-0B BLOCKED).
// NO real data binding here — THQ-5 replaces this with a public-safe adapter.

import type { TradingAgentHQViewModel } from "./viewModel";

export const MOCK_VIEW_MODEL: TradingAgentHQViewModel = {
  mode: "trading_agent_hq",
  meta: {
    lastUpdate: "—",
    source: "mock",
    isStale: true, // mock is never live truth
  },
  safety: {
    liveTradingEnabled: false,
    orderPlacementEnabled: false,
    productionTradingReady: false,
    exchangeManualApproval: "not_approved",
    phase: "M-0B_BLOCKED",
  },
  paper: {
    totalOrderFilled: 30,
    closedCycles: 0,
    sampleStatus: "INSUFFICIENT_SAMPLE",
    paperModeDetected: true,
    edgeStatus: "DATA_GAP", // closedCycles===0 → never edge PASS
    costGateStatus: "PASS",
    costGateBreakdown: {
      roundTripCostPct: 0.14,
      gridSpacingPct: 0.72,
      gridSpacingSource: "dynamicGrid.spacingPct",
      requiredMinSpacingPct: 0.25,
      pass: true,
      warning: false,
      nextAction: "read_only_mock_no_action",
      feeEstimateTotal: 0.05,
      slippageEstimateTotal: 0.02,
      fundingEstimateTotal: 0,
      feePctConfig: 0.05,
      slippagePctConfig: 0.02,
      status: "PASS",
      spacingBufferRatio: 5.142857142857143,
      feeGrindRisk: "HEALTHY_BUFFER",
    },
    runtimeMonitor: {
      cumulativeBuyFillCount: 1460,
      cumulativeSellFillCount: 0,
      sampleBuyFillCount: 14,
      sampleSellFillCount: 0,
      paperNoTradeCount: 122,
      regridCandidateCount: 75,
      latestFillAt: null,
      latestNoTradeAt: null,
      latestRegridCandidateAt: null,
      buyCountStable: true,
      noTradeIncreasing: true,
      regridCandidateIncreasing: true,
      activationAllowed: false,
      priceVsGrid: "BELOW_GRID",
      paperLoopState: "REGRID_REQUIRED",
      monitorStatus: "PASS",
      monitorSummary: "STABLE_RUNTIME_PASS",
    },
    regridReadiness: {
      status: "NOT_READY",
      score: 40,
      passedGates: ["out_of_grid_context", "old_one_sided_exposure_quarantined"],
      failedGates: ["stable_candles_pending", "cooldown_pending", "candidate_grid_missing"],
      warnings: ["old_buy_exposure_quarantined_not_counted_as_closed_cycle"],
      nextAction: "wait_for_stability_cooldown_and_candidate_grid",
      operatorReviewRequired: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    paperEpoch: {
      currentEpochId: "static-grid:BELOW_GRID",
      previousEpochStatus: "OPEN_ONE_SIDED_EXPOSURE",
      previousEpochReason: "old static-grid BUY exposure is quarantined",
      nextEpochCandidateId: null,
      nextEpochStatus: "NOT_READY",
      oldExposurePolicy: [
        "QUARANTINE_OLD_ONE_SIDED_EXPOSURE",
        "DO_NOT_COUNT_AS_CLOSED_CYCLE",
        "DO_NOT_FORCE_SELL",
        "DO_NOT_USE_FOR_EXPECTANCY",
      ],
    },
    indicatorGate: {
      status: "INSUFFICIENT_DATA",
      reasons: ["mock_data_not_runtime_evidence"],
      passed: [],
      failed: ["missing_indicator_evidence"],
      confidence: "low",
      blocking: true,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    canonicalMarketRegime: {
      regime: "UNKNOWN",
      direction: "UNKNOWN",
      confidence: 0,
      confidenceLabel: "low",
      reasons: ["mock_data_not_runtime_evidence"],
      warnings: ["canonical_market_regime_requires_market_snapshot"],
      allowedModes: ["NO_TRADE"],
      blockedModes: ["NEUTRAL_GRID", "DYNAMIC_NEUTRAL_GRID", "PHASE_2B_ACTIVATION"],
      sourcePriority: ["market_snapshot.klines"],
      ignoredLegacyFields: ["latest_decision.market_mode"],
      sourceFreshness: {
        status: "unknown",
        generatedAt: null,
        latestCandleAtByTimeframe: {},
        warnings: ["mock_has_no_freshness_evidence"],
      },
      evidenceCompleteness: {
        status: "missing",
        scorePct: 0,
        availableGroups: [],
        missingGroups: ["multi_timeframe_indicators"],
      },
      shadowOnly: true,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    regimeDiagnostic: {
      decisionRegime: null,
      canonicalRegime: null,
      canonicalDirection: null,
      canonicalConfidence: null,
      canonicalSource: null,
      canonicalReasons: [],
      canonicalComputedAt: null,
      decisionRegimeMismatch: false,
      regimeNullButCanonicalAvailable: false,
      status: "NO_CANONICAL_DATA",
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    volBaselineDiagnostic: {
      volState: null,
      confidence: null,
      baselineSamples1h: null,
      requiredBaselineSamples: null,
      baselineProgressPct: null,
      baselineReadiness: "NO_DATA",
      warning: null,
    },
    eventRiskContext: {
      status: "NO_DATA",
      headlineCount: 0,
      source: null,
      freshness: "unknown",
      updatedAt: null,
      riskLabel: null,
      summary: null,
      warning: "News context missing/stale",
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    regimeTransitionDiagnostic: {
      status: "NOT_CONFIGURED",
      hasHistoryStore: false,
      hysteresisActive: false,
      message: "Regime transition history is not configured",
      warning: "Design-only - no regime behavior change",
    },
    canonicalRegimeGate: {
      status: "UNKNOWN_DATA_BLOCK",
      blocking: true,
      downgradeOnly: true,
      reasons: ["mock_data_not_runtime_evidence", "missing_canonical_market_regime"],
      warnings: ["stricter_only_enforcement_display_only_mock"],
      affectedModes: ["NEUTRAL_GRID", "DYNAMIC_NEUTRAL_GRID", "PHASE_2B_ACTIVATION"],
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    regridReadinessBeforeCanonicalGate: {
      status: "NOT_READY",
      score: 40,
      passedGates: ["out_of_grid_context", "old_one_sided_exposure_quarantined"],
      failedGates: ["stable_candles_pending", "cooldown_pending", "candidate_grid_missing"],
      warnings: ["old_buy_exposure_quarantined_not_counted_as_closed_cycle"],
      nextAction: "wait_for_stability_cooldown_and_candidate_grid",
      operatorReviewRequired: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    regridReadinessAfterCanonicalGate: {
      status: "NOT_READY",
      score: 40,
      passedGates: ["out_of_grid_context", "old_one_sided_exposure_quarantined"],
      failedGates: ["stable_candles_pending", "cooldown_pending", "candidate_grid_missing"],
      warnings: ["old_buy_exposure_quarantined_not_counted_as_closed_cycle"],
      nextAction: "wait_for_stability_cooldown_and_candidate_grid",
      operatorReviewRequired: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    canonicalRegimeGateShadowCompare: {
      changed: false,
      downgradeReason: "mock_already_not_ready",
    },
    canonicalRegimeGateEnforcement: {
      enabled: true,
      mode: "STRICTER_ONLY",
      activeReadinessSource: "regridReadinessAfterCanonicalGate",
      beforeStatus: "NOT_READY",
      afterStatus: "NOT_READY",
      changed: false,
      downgradeReason: "mock_already_not_ready",
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    trendZoneCandidate: {
      buildStatus: "NOT_TREND",
      dir: null,
      pullbackZone: null,
      invalidation: null,
      triggerRule: null,
      targets: { t1: null, t2: null },
      entry: { type: null, hint: null },
      smc: { swingHigh1h: null, swingLow1h: null, eq1h: null, liquidityNote: null },
      warnings: ["mock_data_not_runtime_evidence"],
      shadowOnly: true,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    trendStrategy: {
      enabled: false,
      phase: "T-1_SHADOW",
      status: "NO_TRADE",
      direction: null,
      setupReason: "mock_data_not_runtime_evidence",
      entryZone: null,
      currentPrice: null,
      distanceToEntryZonePct: null,
      invalidation: null,
      target1: null,
      target2: null,
      rewardRisk: null,
      confirmationRequired: false,
      confirmationStatus: "NOT_REQUIRED",
      riskStatus: "PASS",
      oldExposurePolicy: "QUARANTINE_OLD_GRID_EXPOSURE",
      countTowardGridClosedCycles: false,
      countTowardTrendEvidence: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      shadowOnly: true,
      reasons: ["mock_data_not_runtime_evidence"],
      warnings: ["trend_strategy_shadow_only_no_execution"],
    },
    trendPaperEpoch: {
      epochId: "trend-shadow:NONE:NO_TRADE",
      source: "TREND_STRATEGY",
      phase: "T-1_SHADOW",
      status: "NO_TRADE",
      direction: null,
      oldGridExposurePolicy: "QUARANTINE_OLD_GRID_EXPOSURE",
      countTowardGridClosedCycles: false,
      countTowardTrendEvidence: false,
    },
    trendTransitionMonitor: {
      status: "IDLE_NO_TRADE",
      severity: "info",
      message: "ข้อมูลจำลอง: ยังไม่มี trend setup",
      operatorAction: "รอ pullback ใหม่ ห้ามไล่ราคา",
      shouldNotifyOperator: false,
      checkedAt: null,
      watchedFields: {
        trendStatus: "NO_TRADE",
        riskStatus: "NO_TRADE_NEAR_TARGET",
        direction: null,
        currentPrice: null,
        entryZone: null,
        invalidation: null,
        target1: null,
        rewardRisk: null,
      },
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    trendManualPaperArmGate: {
      phase: "T-2_DESIGN",
      status: "NOT_READY",
      requiredConditions: ["trend_status_awaiting_or_setup_ready", "risk_status_pass", "zone_build_ready"],
      passedConditions: [],
      failedConditions: ["trend_status_awaiting_or_setup_ready"],
      operatorActionRequired: false,
      setupId: null,
      expiryAt: null,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      notes: ["ข้อมูลจำลอง: ยังไม่พร้อม arm"],
    },
    trendPaperExecutionPreflight: {
      phase: "T-3_PREFLIGHT",
      status: "NOT_READY",
      requiredInputs: ["trend_status_awaiting_or_setup_ready", "risk_status_pass", "zone_build_ready"],
      passedInputs: [],
      failedInputs: ["trend_status_awaiting_or_setup_ready"],
      setupId: null,
      direction: null,
      entry: null,
      stopLoss: null,
      takeProfit1: null,
      takeProfit2: null,
      rewardRisk: null,
      paperArmAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      journalWriteAllowed: false,
      simulatedFillAllowed: false,
      notes: ["ข้อมูลจำลอง: preflight ยังไม่พร้อม"],
    },
    trendPaperExecutionEngine: {
      enabled: false,
      mode: "PAPER_SIMULATION_ONLY",
      lastAction: "NO_ACTION",
      lastReason: "CONFIG_DISABLED",
      openTrendPaperPosition: null,
      lastEntryAt: null,
      lastExitAt: null,
      trendPaperClosedTrades: 0,
      winRate: null,
      netExpectancyAfterCosts: null,
      paperOnly: true,
      liveActivationAllowed: false,
      exchangeOrderAllowed: false,
    },
    trendPaperArmSession: {
      present: false,
      status: "MISSING",
      sessionId: null,
      direction: null,
      symbol: null,
      startedAt: null,
      expiresAt: null,
      timeRemainingMs: null,
      maxEntries: null,
      usedEntries: null,
      remainingEntries: null,
      maxRiskPerTradePct: null,
      maxSessionRiskPct: null,
      active: false,
      paperOnly: true,
      liveActivationAllowed: false,
      exchangeOrderAllowed: false,
    },
    trendPaperArmIntentBridge: {
      rawStatus: "READY_FOR_OPERATOR_REVIEW",
      effectiveStatus: "READY_FOR_OPERATOR_REVIEW",
      source: "SESSION_MISSING",
      upgradedToArmed: false,
      paperArmIntentRequested: false,
      reasons: ["ข้อมูลจำลอง: ไม่มี session arm intent"],
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    trendPaperEvidenceRunner: {
      evidencePhase: "DISABLED",
      enabled: false,
      simulationEnabled: false,
      evidenceRunnerEnabled: false,
      lastRunAt: null,
      lastDecision: null,
      lastGateStatus: null,
      lastRejectReasons: [],
      dailyEntryCount: 0,
      maxEntriesPerDay: 3,
      dailyLossR: 0,
      cooldownUntil: null,
      openTrendPosition: null,
      trendClosedTrades: 0,
      targetClosedTrades: 30,
      sampleStatus: "INSUFFICIENT_SAMPLE_BOOTSTRAP",
      winRate: null,
      expectancyR: null,
      profitFactor: null,
      maxDrawdownR: null,
      maxConsecutiveLossesObserved: null,
      readyForNextPhase: false,
      stopReason: null,
      liveActivationAllowed: false,
      exchangeOrderAllowed: false,
    },
    reviewReadinessScore: {
      available: true,
      overallScore: 11,
      overallStatus: "NOT_READY",
      scoreType: "REVIEW_READINESS_NOT_ACTIVATION",
      tag: "D5_5_REVIEW_READINESS_NOT_READY",
      activationAllowed: false,
      reviewOnly: true,
      disclaimer: "Review readiness only - not activation, not live, not order placement.",
      dimensions: {
        grid: { status: "NO_REALIZED_EDGE_SAMPLE", score: 0, weight: 35, weightedScore: 0, drivers: ["closedCycles=0"] },
        shadow: { status: "LOW_QUALITY_NOT_READY", score: 11, weight: 35, weightedScore: 3.85, drivers: ["coverage=0.2857", "sampleQuality=LOW"] },
        trend: { status: "NO_DATA_INVALIDATED", score: 0, weight: 20, weightedScore: 0, drivers: ["trendStrategy=INVALIDATED"] },
        noTradeExplanation: { status: "EXPLAINED_WITH_DIAGNOSTICS_GAP", score: 70, weight: 10, weightedScore: 7, drivers: ["diagnosticsGap=true"] },
      },
    },
    operatorSummary: {
      currentPrice: 101.5,
      freshnessStatus: "FRESH",
      latestCandleAt: "2026-06-18T10:00:00.000Z",
      regime: "NO_TRADE",
      direction: "UNKNOWN",
      confidence: 35,
      reviewSamplesUsed: 75,
      reviewTargetSamples: 100,
      reviewSampleGatePassed: false,
      lifetimeExactSamples: 325,
      windowExactSamples: 65,
      currentPriceEligibleExactSamples: null,
      cleanCurrentPriceEligibleSamples: null,
      watchlistStatus: "REGIME_NOT_CONFIRMED",
      cleanReviewCandidates: 0,
      trendSetupDirection: null,
      trendSetupStatus: "NO_TRADE",
      trendRiskStatus: null,
      trendEntryZone: null,
      trendPriceMoveRequiredDirection: null,
      nearCandidateDirection: "SHORT",
      nearCandidateDirectionAlignment: "REGIME_NOT_CONFIRMED",
      nearCandidateQualityStatus: "TARGET_TOO_CLOSE",
      candidateInterpretation: "SHORT exact candidate is REGIME_NOT_CONFIRMED with quality TARGET_TOO_CLOSE",
      mainBlocker: "structured exact candidate geometry missing",
      nextAction: "wait for trend regime confirmation and price pullback before review",
      pullbackGate: {
        pullbackGateStatus: "NO_ALIGNED_RESOLUTION",
        alignedDirection: "UNKNOWN",
        priceDistanceToZonePct: null,
        bestRR: null,
        rrThreshold: null,
        confirmationStatus: "UNKNOWN",
        nextAction: "wait for a valid D8.0 aligned entry resolution",
      },
      pullbackTrigger: {
        status: "NO_GATE",
        triggerPrice: null,
        rawZoneTriggerPrice: null,
        distanceToTriggerAbs: null,
        distanceToTriggerPct: null,
        rrReady: false,
        promotionBlockedBy: ["NO_VALID_PULLBACK_GATE"],
        nextAction: "wait for a valid D8.1 resolver-driven pullback gate",
      },
      pullbackTouch: {
        touchStatus: "NO_TRIGGER_CONTEXT",
        touchType: null,
        lastTouchAt: null,
        lastTouchTimeframe: null,
        candlesSinceTouch: null,
        confirmationWindowStatus: "NOT_AVAILABLE",
        shouldEvaluateConfirmation: false,
        nextAction: "wait for valid D8.2 pullback trigger geometry",
      },
      touchConfirmation: {
        status: "NO_TOUCH_CONTEXT",
        confirmationStatus: "NOT_EVALUATED",
        alignedDirection: "UNKNOWN",
        touchStatus: "NO_TRIGGER_CONTEXT",
        rrReady: false,
        shouldPromoteToReview: false,
        nextAction: "wait for an active touch window and fresh aligned confirmation",
      },
      candidateBottleneck: {
        status: "NO_CONTEXT",
        primaryBlocker: "MISSING_CONTEXT",
        distanceToTriggerAbs: null,
        distanceToTriggerPct: null,
        triggerDistanceClass: "UNKNOWN",
        nextAlgorithmBranch: "NO_ACTION",
        nextAction: "wait for consistent D8.0-D8.4 diagnostic context",
      },
      historicalReplay: {
        status: "NO_REPLAY_DATA",
        dominantBottleneck: "NONE",
        promotableRate: null,
        recommendedNextResearch: "COLLECT_MORE_HISTORY",
        nextAction: "supply approved offline point-in-time replay evidence",
      },
      safety: {
        reviewOnly: true,
        activationAllowed: false,
        paperActivationAllowed: false,
        liveActivationAllowed: false,
        orderAllowed: false,
        shadowOnly: true,
      },
    },
    mtfEntryCandidatePipeline: {
      schemaVersion: 1,
      source: "MTF_ENTRY_CANDIDATE_PIPELINE_V1",
      status: "WARNING_DEGRADED",
      readiness: "REVIEW_NOT_ACTIVATION",
      activationAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      reviewOnly: true,
      shadowOnly: true,
      htfBias: {
        status: "BEARISH",
        confidence: 82,
        source: "mock_runtime_like",
        reasons: ["HTF downtrend"],
        warnings: [],
      },
      zoneCandidate: {
        status: "TARGET_TOO_CLOSE",
        exactSamples: 75,
        windowExactSamples: 70,
        lifetimeExactSamples: 75,
        reviewSamplesUsed: 75,
        requiredExactSamples: 100,
        samplesRemaining: 25,
        sampleCountMeaning: "WINDOW_FOR_RECENT_PATTERN",
        reviewSampleGatePassed: false,
        exactAvgNetRR: 6.1932,
        heuristicAvgNetRR: 1.7058,
        exactVsHeuristicDelta: 4.8687,
        usesExactObFvgZonesCount: 75,
        dominantExactStatus: "EXACT_ZONE_CONFLICT",
        dominantExactReadiness: "TARGET_TOO_CLOSE",
        warningFlags: ["HIGH_TARGET_TOO_CLOSE_RATE", "HIGH_MISSED_FILL_RATE", "REVIEW_NOT_ACTIVATION"],
      },
      triggerReview: {
        status: "INVALIDATION_DOMINATES",
        entryTouched: 21,
        entryTouchRate: 0.28,
        entryNotReached: 0,
        entryNotReachedRate: 0,
        targetAfterEntryTouchRate: 0,
        invalidationAfterEntryTouchRate: 0.9524,
        pending: 11,
      },
      geometry: {
        status: "WARNING_DEGRADED",
        geometryReady: 64,
        noGeometry: 11,
        fillResolutionStatus: "PARTIAL",
        missedFillRate: 0.6719,
        pending: 11,
        notes: ["runtime-like degraded mock", "review-only geometry; no live or paper activation"],
      },
      currentPriceContext: {
        currentPrice: 101.5,
        priceSource: "market_snapshot.15m.close",
        latestCandleAt: "2026-06-18T10:00:00.000Z",
        snapshotGeneratedAt: "2026-06-18T10:01:00.000Z",
        freshnessStatus: "FRESH",
        ageSeconds: 300,
        reevaluationRequired: false,
        notes: ["Latest candle is fresh."],
      },
      currentCandidateReevaluation: {
        status: "CURRENT_PRICE_CONFIRMED",
        previousAnalysisPrice: 101,
        currentPrice: 101.5,
        priceMovePct: 0.5,
        reason: "Current price is fresh and close enough to the prior analysis context.",
      },
      sampleAccounting: {
        lifetimeExactSamples: 75,
        windowExactSamples: 70,
        currentPriceEligibleExactSamples: 12,
        reviewTargetSamples: 100,
        reviewSamplesUsed: 75,
        reviewSamplesRemaining: 25,
        sampleSource: "LIFETIME_CUMULATIVE",
        isMonotonicExpected: true,
        canDecrease: false,
        explanation: "Lifetime cumulative exact samples drive review progress.",
        warnings: [],
      },
      verdict: {
        status: "PROMISING_GEOMETRY_BUT_EXECUTION_NOT_READY",
        summary: "Exact Zone มี RR geometry ดีกว่า heuristic แต่ execution outcome ยังไม่พร้อม",
        blockers: [
          "exact samples 75/100 - ขาด exact samples อีก 25",
          "TARGET_TOO_CLOSE สูง (50/75)",
          "Missed fill rate สูง (67%)",
          "หลัง entry touch ยังไม่เห็น target ชนะ invalidation",
          "invalidation dominates after entry touch",
        ],
        nextAction: "continue_collecting_exact_zone_and_shadow_outcome_evidence",
      },
    },
    mtfExactZoneFailureAttribution: {
      schemaVersion: 1,
      source: "MTF_EXACT_ZONE_FAILURE_ATTRIBUTION_V1",
      status: "GEOMETRY_PROMISING_EXECUTION_WEAK",
      readiness: "REVIEW_NOT_ACTIVATION",
      activationAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      reviewOnly: true,
      shadowOnly: true,
      sample: {
        lifetimeExactSamples: 325,
        windowExactSamples: 65,
        currentPriceEligibleExactSamples: null,
        reviewTargetSamples: 100,
        sampleGatePassed: true,
        sampleInterpretation: "Sample gate passed; quality gates still block review.",
      },
      geometryEdge: {
        exactAvgNetRR: 5.06,
        heuristicAvgNetRR: 1.62,
        delta: 3.44,
        ratio: 3.12,
        status: "GEOMETRY_EDGE_STRONG",
      },
      failureRates: {
        targetTooCloseRate: 0.615,
        missedFillRate: 0.797,
        entryTouchRate: 0.2,
        targetAfterTouchRate: 0,
        invalidationAfterTouchRate: 0.72,
      },
      failureAttribution: {
        dominantFailures: [
          { code: "TARGET_TOO_CLOSE_DOMINATES", severity: "BLOCKER", evidence: ["TARGET_TOO_CLOSE 40/65"], interpretation: "Target-too-close cases dominate the window." },
          { code: "MISSED_FILL_DOMINATES", severity: "BLOCKER", evidence: ["missedFillRate=79.7%"], interpretation: "Fill reachability is still weak." },
          { code: "TARGET_AFTER_TOUCH_NOT_PROVEN", severity: "BLOCKER", evidence: ["targetAfterTouchRate=0%"], interpretation: "Target reach after entry touch is not proven." },
          { code: "CURRENT_PRICE_ELIGIBLE_MISSING", severity: "BLOCKER", evidence: ["currentPriceEligibleExactSamples is missing"], interpretation: "Current market actionability is not proven." },
        ],
      },
      cleanSubsetGate: {
        status: "NOT_READY",
        passed: ["lifetimeExactSamples >= 100", "geometry edge promising"],
        failed: ["targetTooCloseRate > 0.4", "missedFillRate > 0.5", "targetAfterTouchRate < 0.25", "currentPriceEligibleExactSamples missing"],
        thresholds: {
          minLifetimeExactSamples: 100,
          maxTargetTooCloseRate: 0.4,
          maxMissedFillRate: 0.5,
          minEntryTouchRate: 0.35,
          minTargetAfterTouchRate: 0.25,
          maxInvalidationAfterTouchRate: 0.5,
          currentPriceEligibleRequired: true,
        },
      },
      nextAction: {
        primary: "isolate clean exact-zone subset before review",
        reviewTasks: ["separate target-too-close cases", "collect current-price eligible exact subset evidence"],
        doNotDo: ["do not activate paper/live", "do not place trades", "do not change entry logic"],
      },
    },
    currentPriceEligibleExactSubset: {
      schemaVersion: 1,
      source: "CURRENT_PRICE_ELIGIBLE_EXACT_SUBSET_V1",
      status: "GEOMETRY_INPUTS_MISSING",
      readiness: "REVIEW_NOT_ACTIVATION",
      activationAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      reviewOnly: true,
      shadowOnly: true,
      currentPrice: {
        value: 101.5,
        source: "market_snapshot.15m.close",
        latestCandleAt: "2026-06-18T10:00:00.000Z",
        freshnessStatus: "FRESH",
        ageSeconds: 300,
      },
      sampleAccounting: {
        lifetimeExactSamples: 325,
        windowExactSamples: 65,
        currentPriceEligibleExactSamples: null,
        cleanCurrentPriceEligibleSamples: null,
        geometryInputSamples: 0,
        geometryMissingSamples: 0,
      },
      eligibilityFilters: {
        totalCandidates: 0,
        freshCandidates: 0,
        currentPriceInsideOrNearEntry: 0,
        missedCandidates: 0,
        invalidatedCandidates: 0,
        targetTooCloseCandidates: 0,
        costTooHighCandidates: 0,
        cleanCandidates: 0,
      },
      cleanSubsetGate: {
        status: "NOT_READY",
        passed: ["fresh current price"],
        failed: ["structured exact candidate geometry missing"],
        thresholds: {
          minCleanEligibleCandidates: 10,
          maxTargetTooCloseRate: 0.4,
          maxMissedFillRate: 0.5,
          minEntryTouchRate: 0.35,
          minTargetAfterTouchRate: 0.25,
          maxInvalidationAfterTouchRate: 0.5,
          requireFreshCurrentPrice: true,
          requireStructuredGeometry: true,
        },
      },
      topCandidates: [],
      compactTopCandidates: [],
      dedupSummary: {
        rawCandidates: 0,
        uniqueCandidates: 0,
        duplicateCandidates: 0,
      },
      priceSourceAudit: {
        subsetPriceSource: "market_snapshot.15m.close",
        snapshotPriceSource: "not_available_at_snapshot_build",
        subsetCurrentPrice: 101.5,
        snapshotCurrentPrice: null,
        previousAnalysisPriceSource: null,
        previousAnalysisPrice: null,
        previousAnalysisDriftPct: null,
        priceSourceConsistent: false,
        notes: ["Snapshot currentPrice is missing; subset uses currentPriceContext as source of truth."],
      },
      requiredGeometryInputs: ["direction", "entryLow/entryHigh or entry", "stopLoss or invalidation", "target1 or target", "netRR or exactNetRR"],
      warnings: ["Exact-zone evidence is aggregate-only; current-price eligibility cannot be computed without per-candidate geometry."],
      nextAction: "add exact candidate geometry snapshot fields to observability log",
    },
    currentPriceConsistencyAudit: {
      schemaVersion: 1,
      source: "CURRENT_PRICE_CONSISTENCY_AUDIT_V1",
      status: "CONSISTENT",
      canonicalCurrentPrice: {
        value: 101.5,
        source: "market_snapshot.15m.close",
        latestCandleAt: "2026-06-18T10:00:00.000Z",
        freshnessStatus: "FRESH",
        ageSeconds: 300,
      },
      detectedConsumers: [
        {
          path: "mtfEntryCandidatePipeline.currentPriceContext.currentPrice",
          value: 101.5,
          source: "mtfEntryCandidatePipeline.currentPriceContext",
          priceDelta: 0,
          priceDeltaPct: 0,
          status: "MATCH",
        },
        {
          path: "currentPriceEligibleExactSubset.currentPrice.value",
          value: 101.5,
          source: "market_snapshot.15m.close",
          priceDelta: 0,
          priceDeltaPct: 0,
          status: "MATCH",
        },
      ],
      affectedConditions: [
        {
          condition: "price_inside_entry_zone_or_edge",
          previousValue: null,
          currentPriceBasedValue: null,
          impact: "UNKNOWN",
          explanation: "Current price re-evaluation does not downgrade this condition.",
        },
      ],
      currentPriceReevaluation: {
        trendZoneStatus: "UNKNOWN",
        distanceToEntryZonePct: null,
        distanceToEntryZoneAbs: null,
        priceMoveRequiredDirection: "UNKNOWN",
        explanation: "Current price cannot confirm entry zone status.",
      },
      recommendations: ["Continue using canonical current price for trend gate diagnostics."],
      pricePropagationAudit: {
        staleConsumerCount: 0,
        propagatedConsumerCount: 2,
        previousAnalysisPriceCount: 0,
        notes: ["All available current-price consumers match the canonical current price."],
      },
      safety: {
        reviewOnly: true,
        activationAllowed: false,
        paperActivationAllowed: false,
        liveActivationAllowed: false,
        orderAllowed: false,
      },
    },
    regimeAwareExactCandidateWatchlist: {
      schemaVersion: 1,
      source: "REGIME_AWARE_EXACT_CANDIDATE_WATCHLIST_V1",
      status: "REGIME_NOT_CONFIRMED",
      readiness: "REVIEW_NOT_ACTIVATION",
      activationAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      reviewOnly: true,
      shadowOnly: true,
      currentMarket: {
        currentPrice: 101.5,
        freshnessStatus: "FRESH",
        regime: "NO_TRADE",
        direction: "UNKNOWN",
        confidence: 35,
        trendZoneStatus: "NO_ACTIVE_TREND_ZONE",
        noZoneReason: "No active trend zone exists under the current regime.",
        latestCandleAt: "2026-06-18T10:00:00.000Z",
        ageSeconds: 300,
      },
      watchlistSummary: {
        totalCandidates: 65,
        uniqueCandidates: 48,
        watchCandidates: 1,
        waitingPullbackCandidates: 0,
        regimeBlockedCandidates: 1,
        qualityRejectedCandidates: 0,
        degradedWatchCandidates: 0,
        missedCandidates: 44,
        invalidatedCandidates: 4,
        cleanReviewCandidates: 0,
      },
      watchlistDedupSummary: {
        rawWatchCandidates: 1,
        uniqueWatchCandidates: 1,
        duplicateWatchCandidates: 0,
        clusteringTolerance: "entry/target rounded to 0.1 USDT; stop grouped within 1 USDT",
      },
      compactSummary: {
        currentPrice: 101.5,
        freshnessStatus: "FRESH",
        regime: "NO_TRADE",
        direction: "UNKNOWN",
        watchlistStatus: "REGIME_NOT_CONFIRMED",
        cleanReviewCandidates: 0,
        nextAction: "wait for trend regime confirmation and price pullback before review",
        topCandidateDisplayLimit: 3,
        detailsCollapsedByDefault: true,
      },
      topWatchCandidates: [{
        id: "short-watch-63654",
        direction: "SHORT",
        directionAlignment: "REGIME_NOT_CONFIRMED",
        actionability: "WAIT_FOR_REGIME_CONFIRMATION",
        clean: false,
        currentPriceStatus: "WAITING_PULLBACK_TO_ENTRY",
        qualityStatus: "TARGET_TOO_CLOSE",
        entry: 63654.92,
        stopLoss: 64200,
        target1: 62900,
        netRR: 1.1,
        distanceToEntryPct: 1.49,
        priceMoveRequiredDirection: "UP_TO_ENTRY",
        occurrenceCount: 1,
        representativeStopLoss: 64200,
        stopLossRange: null,
        blockers: ["regime not confirmed", "price not near entry", "TARGET_TOO_CLOSE"],
        watchCondition: "รอราคาเข้าใกล้ 63654.92 และต้องเห็น regime/trend confirmation ใหม่ก่อน review",
        doNotDo: ["do not treat as entry signal", "do not activate paper/live", "do not place order"],
      }],
      nextTriggerChecklist: {
        regimeRequired: ["confirm trend regime"],
        priceRequired: ["wait for price near entry"],
        confirmationRequired: ["wait for 5m confirmation"],
        qualityRequired: ["clear target-too-close"],
        dataRequired: [],
      },
      verdict: {
        status: "WAIT_FOR_REGIME_AND_PRICE",
        summary: "Exact candidates are watchlist-only until regime and price confirm.",
        nextAction: "wait for trend regime confirmation and price pullback before review",
      },
    },
    entryCandidateResolution: {
      schemaVersion: 1,
      source: "ENTRY_CANDIDATE_RESOLVER_V1",
      entryResolutionStatus: "NO_ALIGNED_SETUP",
      alignedDirection: "UNKNOWN",
      priceLocation: "NO_ZONE",
      currentPrice: 101.5,
      alignedEntryZone: null,
      rrBest: null,
      rrThreshold: 1.2,
      rrThresholdSource: "trendStrategy.DEFAULT_MIN_RR",
      rejectedOppositeCount: 0,
      nextAction: "wait for a confirmed canonical trend and aligned entry-zone evidence",
      blockers: ["NO_ALIGNED_SETUP"],
      doNotDo: [
        "do not treat diagnostics as an entry signal",
        "do not activate paper or live trading",
        "do not place or cancel orders",
      ],
      detailsCollapsedByDefault: true,
      rrScenarios: [],
      rejectedOppositeCandidates: [],
      activationAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      reviewOnly: true,
      shadowOnly: true,
    },
    resolverDrivenPullbackGate: {
      schemaVersion: 1,
      source: "RESOLVER_DRIVEN_PULLBACK_GATE_V1",
      readiness: "REVIEW_NOT_ACTIVATION",
      status: "NO_ALIGNED_RESOLUTION",
      alignedDirection: "UNKNOWN",
      currentPrice: null,
      zone: null,
      zoneTolerance: null,
      priceDistanceToZonePct: null,
      bestRR: null,
      rrThreshold: null,
      rrStatus: "UNKNOWN",
      confirmationStatus: "UNKNOWN",
      blockers: ["NO_ALIGNED_RESOLUTION"],
      nextAction: "wait for a valid D8.0 aligned entry resolution",
      doNotDo: [
        "do not treat diagnostics as an entry signal",
        "do not activate paper or live trading",
        "do not place or cancel orders",
      ],
      detailsCollapsedByDefault: true,
      activationAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      reviewOnly: true,
      shadowOnly: true,
    },
    pullbackTriggerThresholds: {
      schemaVersion: 1,
      source: "PULLBACK_TRIGGER_THRESHOLDS_V1",
      readiness: "REVIEW_NOT_ACTIVATION",
      status: "NO_GATE",
      alignedDirection: "UNKNOWN",
      currentPrice: null,
      rawZoneLow: null,
      rawZoneHigh: null,
      expandedZoneLow: null,
      expandedZoneHigh: null,
      triggerPrice: null,
      rawZoneTriggerPrice: null,
      distanceToTriggerAbs: null,
      distanceToTriggerPct: null,
      bestRR: null,
      rrThreshold: null,
      rrReady: false,
      confirmationRequired: false,
      promotionBlockedBy: ["NO_VALID_PULLBACK_GATE"],
      nextAction: "wait for a valid D8.1 resolver-driven pullback gate",
      activationAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      reviewOnly: true,
      shadowOnly: true,
    },
    pullbackZoneTouchEvidence: {
      schemaVersion: 1,
      source: "PULLBACK_ZONE_TOUCH_EVIDENCE_V1",
      readiness: "REVIEW_NOT_ACTIVATION",
      status: "NO_TRIGGER_CONTEXT",
      alignedDirection: "UNKNOWN",
      currentPrice: null,
      rawZoneLow: null,
      rawZoneHigh: null,
      expandedZoneLow: null,
      expandedZoneHigh: null,
      triggerPrice: null,
      lastTouchAt: null,
      lastTouchTimeframe: null,
      candlesSinceTouch: null,
      touchType: null,
      deepestTouchPrice: null,
      touchDistancePct: null,
      confirmationWindowCandles: null,
      confirmationWindowStatus: "NOT_AVAILABLE",
      shouldEvaluateConfirmation: false,
      blockers: ["NO_TRIGGER_CONTEXT"],
      nextAction: "wait for valid D8.2 pullback trigger geometry",
      activationAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      reviewOnly: true,
      shadowOnly: true,
    },
    touchAwareConfirmationReview: {
      schemaVersion: 1,
      source: "TOUCH_AWARE_CONFIRMATION_REVIEW_V1",
      readiness: "REVIEW_NOT_ACTIVATION",
      status: "NO_TOUCH_CONTEXT",
      alignedDirection: "UNKNOWN",
      touchStatus: "NO_TRIGGER_CONTEXT",
      touchType: null,
      confirmationWindowStatus: "NOT_AVAILABLE",
      currentPrice: null,
      triggerPrice: null,
      rawZoneLow: null,
      rawZoneHigh: null,
      expandedZoneLow: null,
      expandedZoneHigh: null,
      bestRR: null,
      rrThreshold: null,
      rrReady: false,
      confirmationStatus: "NOT_EVALUATED",
      confirmationTimeframesUsed: [],
      confirmationVotes: [],
      shouldPromoteToReview: false,
      blockers: ["NO_TOUCH_CONTEXT"],
      nextAction: "wait for an active touch window and fresh aligned confirmation",
      activationAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      reviewOnly: true,
      shadowOnly: true,
    },
    noReviewCandidateBottleneckResolver: {
      schemaVersion: 1,
      source: "NO_REVIEW_CANDIDATE_BOTTLENECK_RESOLVER_V1",
      readiness: "REVIEW_NOT_ACTIVATION",
      status: "NO_CONTEXT",
      primaryBlocker: "MISSING_CONTEXT",
      contributingBlockers: [],
      alignedDirection: "UNKNOWN",
      currentPrice: null,
      triggerPrice: null,
      distanceToTriggerAbs: null,
      distanceToTriggerPct: null,
      bestRR: null,
      rrThreshold: null,
      rrReady: false,
      touchStatus: "UNKNOWN",
      confirmationStatus: "UNKNOWN",
      d8Statuses: {
        d8_0: "UNKNOWN",
        d8_1: "UNKNOWN",
        d8_2: "UNKNOWN",
        d8_3: "UNKNOWN",
        d8_4: "UNKNOWN",
      },
      triggerDistanceClass: "UNKNOWN",
      continuationEvidence: {
        status: "INSUFFICIENT",
        timeframesUsed: [],
        reasons: [],
      },
      nextAlgorithmBranch: "NO_ACTION",
      nextAction: "wait for consistent D8.0-D8.4 diagnostic context",
      doNotDo: [
        "do not move the trigger or create a candidate",
        "do not activate paper or live behavior",
      ],
      activationAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      reviewOnly: true,
      shadowOnly: true,
    },
    historicalReplayCandidateScarcityReview: {
      schemaVersion: 1,
      source: "HISTORICAL_REPLAY_CANDIDATE_SCARCITY_REVIEW_V1",
      readiness: "REVIEW_NOT_ACTIVATION",
      status: "NO_REPLAY_DATA",
      replayWindow: {
        timeframe: "5M",
        startAt: null,
        endAt: null,
        candleCount: 0,
        sampleQuality: "NO_SAMPLE",
      },
      funnelCounts: {
        totalEvaluationPoints: 0,
        alignedContextCount: 0,
        d8_0AlignedCandidateCount: 0,
        rrReadyCount: 0,
        waitingForTriggerCount: 0,
        triggerReachedCount: 0,
        zoneTouchedCount: 0,
        confirmationWindowActiveCount: 0,
        confirmationAlignedCount: 0,
        promotableReviewCandidateCount: 0,
      },
      funnelRates: {
        alignedContextRate: null,
        rrReadyRate: null,
        triggerReachedRate: null,
        zoneTouchedRate: null,
        confirmationAlignedRate: null,
        promotableRate: null,
      },
      blockerDistribution: {
        RR_NOT_READY: 0,
        WAITING_FOR_PULLBACK_TRIGGER: 0,
        NO_TOUCH_EVIDENCE: 0,
        TOUCH_WINDOW_EXPIRED: 0,
        CONFIRMATION_NOT_READY: 0,
        CONFIRMATION_CONFLICTING: 0,
        SAFETY_BLOCKED: 0,
        NO_CONTEXT: 0,
      },
      triggerDistanceBuckets: {
        AT_TRIGGER: 0,
        NEAR: 0,
        MID_RANGE: 0,
        FAR: 0,
      },
      dominantBottleneck: "NONE",
      hypothesis: "INSUFFICIENT_HISTORY",
      recommendedNextResearch: "COLLECT_MORE_HISTORY",
      blockers: [],
      nextAction: "supply approved offline point-in-time replay evidence",
      doNotDo: [
        "do not implement a continuation branch from replay output alone",
        "do not create candidates, activate trading, place orders, or write runtime data",
      ],
      activationAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      reviewOnly: true,
      shadowOnly: true,
    },
    shadowEvidenceCoverage: {
      status: "NOT_READY",
      coverageScore: 0.2857,
      requirementsMet: 2,
      requirementsTotal: 7,
      requirements: [
        { id: "context_ready_setups", met: true, current: 48, target: 30, remaining: 0, unit: "samples", note: "Collect context-ready setups." },
        { id: "context_ready_resolved", met: true, current: 39, target: 30, remaining: 0, unit: "samples", note: "Collect context-ready resolved observations." },
        { id: "range_subset", met: false, current: 0, target: 10, remaining: 10, unit: "samples", note: "Collect RANGE-context setups." },
        { id: "entry_touch", met: false, current: 5, target: 20, remaining: 15, unit: "samples", note: "Collect entry-touch observations." },
        { id: "price_context_diversity", met: false, current: 1, target: 2, remaining: 1, unit: "buckets", note: "Collect a second price context bucket." },
        { id: "dynamic_grid_diversity", met: false, current: 1, target: 2, remaining: 1, unit: "buckets", note: "Collect a second dynamic grid context bucket." },
        { id: "unknown_context_dilution", met: false, current: 192, target: 263, remaining: 71, unit: "context_ready_samples", note: "Collect context-ready samples to dilute UNKNOWN context." },
      ],
      nextEvidenceMilestone: {
        id: "PRICE_CONTEXT_DIVERSITY",
        remaining: 1,
        unit: "buckets",
        description: "Collect setups in one more price context bucket.",
      },
    },
    noTradeReasonAnalysis: {
      status: "BOTH_PATHS_BLOCKED",
      activationAllowed: false,
      reviewOnly: true,
      activationBlocked: true,
      gridBlocked: true,
      trendBlocked: true,
      diagnosticsGap: true,
      primaryReason: {
        code: "GRID_EXPOSURE_GUARD_PAUSE",
        category: "GRID_EXPOSURE",
        label: "Grid exposure guard paused new grid entries",
      },
      tag: "D5_4_NO_TRADE_OVERDETERMINED_BOTH_PATHS_BLOCKED",
    },
    // T-3H-6-a: empty decision-log summary (mock has no log data)
    trendEvidenceDecisionSummary: {
      available: false,
      totalRecords: 0,
      windowStart: null,
      windowEnd: null,
      latestRecordedAt: null,
      decisionCounts: {},
      gateStatusCounts: {},
      rejectReasonCounts: {},
      topRejectReasons: [],
      staleCycleEstimate: null,
      lastRejectReasons: [],
      sampleWarning: true,
      // D5.2-c: no shadow outcome summary in mock (exercises the fallback path)
      shadowOutcomeSummary: null,
      exactZoneComparisonSummary: {
        schemaVersion: 1,
        sampleTier: "NO_DATA",
        exactSamples: 0,
        heuristicSamples: 0,
        exactAvgNetRR: null,
        heuristicAvgNetRR: null,
        avgExactVsHeuristicDelta: null,
        exactPassCount: 0,
        exactPassRate: null,
        exactDataStatusCounts: {},
        exactReadinessCounts: {},
        usesExactObFvgZonesCount: 0,
        fillResolutionInputSamples: 0,
        fillResolutionInputMissing: 0,
        fillResolutionGeometryReadyCount: 0,
        dominantExactStatus: null,
        dominantExactReadiness: null,
        fillResolution: {
          status: "NOT_CONFIGURED",
          totalResolvable: 0,
          filled: 0,
          missed: 0,
          pending: 0,
          invalidationFirst: 0,
          missedFillRate: null,
        },
        warningFlags: ["REVIEW_NOT_ACTIVATION"],
        rrMetricScope: "TOP_CLEAN_CANDIDATE",
        readinessMetricScope: "AGGREGATE_WORST_OF_ALL_ZONES",
        conflictLabelNote: "EXACT_ZONE_CONFLICT may aggregate target-too-close, cost-too-high, or true MTF conflict. Check readiness breakdown.",
        conflictBreakdown: {
          TARGET_TOO_CLOSE: 0,
          COST_TOO_HIGH: 0,
          CONFLICTING_MTF: 0,
          other: {},
        },
        readiness: "NO_DATA",
        source: "EXACT_ZONE_COMPARISON_SUMMARY_V1",
      },
      mtfObFvgShadowSummary: {
        available: false,
        totalShadowSamples: 0,
        samplesWithRefinement: 0,
        samplesWithNoData: 0,
        averageCurrentRawRR: null,
        averageCurrentNetRR: null,
        averageRefinedRawRR: null,
        averageRefinedNetRR: null,
        averageRrImprovement: null,
        averageNetRrImprovement: null,
        passStaticCount: 0,
        passNetCount: 0,
        qualityScoreAverage: null,
        classificationCounts: {},
        dataStatusCounts: {},
        exactZoneSamples: 0,
        exactZoneDataStatusCounts: {},
        exactZoneReadinessCounts: {},
        usesExactObFvgZonesCount: 0,
        exactAvgNetRR: null,
        exactVsHeuristicAvgDelta: null,
        latestSnapshot: null,
        sampleWarning: true,
      },
    },
    // T-3H-6-b: display config unknown in mock (UI shows defaults as "config")
    trendPaperConfigPublic: {
      minRewardRisk: null,
      feePct: null,
      slippagePct: null,
    },
    trendEdgeReview: {
      phase: "T-4_EDGE_REVIEW",
      status: "INSUFFICIENT_DATA",
      trendClosedTrades: 0,
      sampleTier: "none",
      winRate: null,
      averageWinR: null,
      averageLossR: null,
      expectancyR: null,
      netExpectancyAfterCosts: null,
      profitFactor: null,
      maxDrawdownR: null,
      maxConsecutiveLosses: null,
      riskOfRuinEstimate: null,
      costDrag: null,
      slippageAttribution: null,
      fundingAttribution: null,
      invalidRiskModelCount: 0,
      invalidMissingStopLossCount: 0,
      decision: "HOLD",
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      notes: ["ข้อมูลจำลอง: ยังไม่มี closed trend trade"],
    },
    regimeEvidence: {
      evidenceCompleteness: {
        status: "partial",
        scorePct: 60,
        availableCount: 3,
        expectedCount: 5,
      },
      sourceFreshness: {
        latestDecisionAt: null,
        marketSnapshotAt: null,
        planStatusStateAt: null,
        warnings: [],
      },
      decision: {
        marketMode: "GRID_NEUTRAL",
        regime: "RANGE",
        trendDir: null,
        trendTriggerRule: null,
        trendInvalidation: null,
        smcBias: null,
        structureState: null,
        bos: null,
        choch: null,
        mss: null,
        sweep: null,
        obContext: null,
        fvgContext: null,
      },
      indicators: {
        adx: { value: null, source: "missing" },
        plusDI: { value: null, source: "missing" },
        minusDI: { value: null, source: "missing" },
        rsi: { value: null, source: "missing" },
        atr: { value: null, source: "missing" },
        atrPct: { value: null, source: "missing" },
        bbw: { value: null, source: "missing" },
        macd: { value: null, source: "missing" },
        macdSignal: { value: null, source: "missing" },
        macdHistogram: { value: null, source: "missing" },
        emaSlope: { value: null, source: "missing" },
      },
      indicatorEvidence: {
        source: "market_snapshot",
        calculatedAt: null,
        candleCount: 0,
        timeframe: "15m",
        freshness: {
          latestCandleAt: null,
          ageMs: null,
        },
        missingFields: ["adx", "plusDI", "minusDI", "rsi", "macd"],
        notes: ["insufficient_candles"],
      },
      derivatives: {
        oiBias: null,
        oiChange: null,
        fundingRate: null,
        fundingBias: null,
        fundingRisk: null,
        openInterest: null,
        derivativesBias: null,
      },
      obGate: {
        status: null,
        reason: null,
        score: null,
        passed: null,
        blockedReason: null,
      },
      missingFields: ["indicators.adx", "indicators.plusDI", "indicators.minusDI", "indicators.rsi"],
      availableFields: ["decision.marketMode", "decision.regime"],
      notes: ["indicator_not_available_in_runtime_source"],
    },
    dynamicRegrid: {
      marketMode: "GRID_NEUTRAL",
      regime: "RANGE",
      priceVsGrid: "BELOW_GRID",
      paperLoopState: "REGRID_REQUIRED",
      lastNoTradeReason: "price_below_grid_lower",
      currentPrice: null,
      gridLower: null,
      gridUpper: null,
      gridMid: null,
      buyFillCount: 14,
      sellFillCount: 0,
      closedCycles: 0,
      candidate: {
        candidateStatus: "NO_TRADE",
        candidateReason: "Phase 1 read-only evaluator; activation blocked",
        cooldownRemaining: 4,
        stableCandleCount: 0,
        activationAllowed: false,
      },
    },
  },
  topHud: {
    marketMood: "UNKNOWN",
    simEquity: null,
    dailyPnl: null,
    riskHeat: "UNKNOWN",
    agentsActive: 2,
  },
  bottomLog: [
    { ts: "—", type: "SYSTEM", text: "TradingAgentHQ ตัวอย่าง (ข้อมูลจำลอง — ไม่ใช่ของจริง)" },
    { ts: "—", type: "FILL_RESULT", text: "บันทึก paper MARKET fill (จำลอง)", agentId: "grid_bot" },
    { ts: "—", type: "DECISION", text: "รอประเมิน regime (จำลอง)", agentId: "market_regime" },
    { ts: "—", type: "ALERT", text: "รอบปิดครบ = 0 → ยังไม่มีข้อมูลรอบปิด (honest)", agentId: "risk_manager" },
  ],
  agents: {
    grid_bot: {
      id: "grid_bot", status: "running", visualStates: ["running", "balancing_orders"],
      animation: "grid_working", bubble: "กำลังจัดสมดุลคำสั่ง… (จำลอง)",
      currentTask: "รอบ Paper grid", lastAction: "paper MARKET fill (จำลอง)",
      metric: "fills: 30", confidence: "n/a (paper)",
    },
    trend_bot: {
      id: "trend_bot", status: "unknown", visualStates: ["idle"],
      animation: "idle", bubble: "รอข้อมูล (จำลอง)",
      currentTask: "สแกนโมเมนตัม", lastAction: "—", metric: null, confidence: null,
    },
    risk_manager: {
      id: "risk_manager", status: "guarding", visualStates: ["calm"],
      animation: "idle", bubble: "เฝ้าระวังเงินทุน (จำลอง)",
      currentTask: "เฝ้าความเสี่ยง", lastAction: "ตรวจ flag", metric: "เงินจริง: ปิด", confidence: "safe-mode",
    },
    news_analyst: {
      id: "news_analyst", status: "unknown", visualStates: ["idle"],
      animation: "idle", bubble: "ไม่มีฟีดข่าว (จำลอง)",
      currentTask: "สแกนข่าว", lastAction: "—", metric: null, confidence: null,
    },
    market_regime: {
      id: "market_regime", status: "scanning", visualStates: ["thinking"],
      animation: "idle", bubble: "กำลังอ่าน regime… (จำลอง)",
      currentTask: "จำแนก regime", lastAction: "รอ decision", metric: "mode: UNKNOWN", confidence: null,
    },
    memory_brain: {
      id: "memory_brain", status: "logging", visualStates: ["idle"],
      animation: "idle", bubble: "กำลังบันทึก journal (จำลอง)",
      currentTask: "บันทึกตรวจสอบ (audit log)", lastAction: "เพิ่มเหตุการณ์", metric: null, confidence: null,
    },
  },
};
