// dashboard/lib/trading-agent-hq/mockState.ts
// TradingAgentHQ — THQ-4 static mock ViewModel.
// HONEST mock: reflects real M-0Z-6 posture (paper LIVE, closedCycles=0 DATA_GAP, M-0B BLOCKED).
// NO real data binding here — THQ-5 replaces this with a public-safe adapter.

import type { TradingAgentHQViewModel } from "./viewModel";

export const MOCK_VIEW_MODEL: TradingAgentHQViewModel = {
  mode: "trading_agent_hq",
  meta: {
    lastUpdate: "—",
    source: "mock",
    isStale: true, // mock is never live truth
  },
  safety: {
    liveTradingEnabled: false,
    orderPlacementEnabled: false,
    productionTradingReady: false,
    exchangeManualApproval: "not_approved",
    phase: "M-0B_BLOCKED",
  },
  paper: {
    totalOrderFilled: 30,
    closedCycles: 0,
    sampleStatus: "INSUFFICIENT_SAMPLE",
    paperModeDetected: true,
    edgeStatus: "DATA_GAP", // closedCycles===0 → never edge PASS
    costGateStatus: "PASS",
    runtimeMonitor: {
      cumulativeBuyFillCount: 1460,
      cumulativeSellFillCount: 0,
      sampleBuyFillCount: 14,
      sampleSellFillCount: 0,
      paperNoTradeCount: 122,
      regridCandidateCount: 75,
      latestFillAt: null,
      latestNoTradeAt: null,
      latestRegridCandidateAt: null,
      buyCountStable: true,
      noTradeIncreasing: true,
      regridCandidateIncreasing: true,
      activationAllowed: false,
      priceVsGrid: "BELOW_GRID",
      paperLoopState: "REGRID_REQUIRED",
      monitorStatus: "PASS",
      monitorSummary: "STABLE_RUNTIME_PASS",
    },
    regridReadiness: {
      status: "NOT_READY",
      score: 40,
      passedGates: ["out_of_grid_context", "old_one_sided_exposure_quarantined"],
      failedGates: ["stable_candles_pending", "cooldown_pending", "candidate_grid_missing"],
      warnings: ["old_buy_exposure_quarantined_not_counted_as_closed_cycle"],
      nextAction: "wait_for_stability_cooldown_and_candidate_grid",
      operatorReviewRequired: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    paperEpoch: {
      currentEpochId: "static-grid:BELOW_GRID",
      previousEpochStatus: "OPEN_ONE_SIDED_EXPOSURE",
      previousEpochReason: "old static-grid BUY exposure is quarantined",
      nextEpochCandidateId: null,
      nextEpochStatus: "NOT_READY",
      oldExposurePolicy: [
        "QUARANTINE_OLD_ONE_SIDED_EXPOSURE",
        "DO_NOT_COUNT_AS_CLOSED_CYCLE",
        "DO_NOT_FORCE_SELL",
        "DO_NOT_USE_FOR_EXPECTANCY",
      ],
    },
    indicatorGate: {
      status: "INSUFFICIENT_DATA",
      reasons: ["mock_data_not_runtime_evidence"],
      passed: [],
      failed: ["missing_indicator_evidence"],
      confidence: "low",
      blocking: true,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    canonicalMarketRegime: {
      regime: "UNKNOWN",
      direction: "UNKNOWN",
      confidence: 0,
      confidenceLabel: "low",
      reasons: ["mock_data_not_runtime_evidence"],
      warnings: ["canonical_market_regime_requires_market_snapshot"],
      allowedModes: ["NO_TRADE"],
      blockedModes: ["NEUTRAL_GRID", "DYNAMIC_NEUTRAL_GRID", "PHASE_2B_ACTIVATION"],
      sourcePriority: ["market_snapshot.klines"],
      ignoredLegacyFields: ["latest_decision.market_mode"],
      sourceFreshness: {
        status: "unknown",
        generatedAt: null,
        latestCandleAtByTimeframe: {},
        warnings: ["mock_has_no_freshness_evidence"],
      },
      evidenceCompleteness: {
        status: "missing",
        scorePct: 0,
        availableGroups: [],
        missingGroups: ["multi_timeframe_indicators"],
      },
      shadowOnly: true,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    canonicalRegimeGate: {
      status: "UNKNOWN_DATA_BLOCK",
      blocking: true,
      downgradeOnly: true,
      reasons: ["mock_data_not_runtime_evidence", "missing_canonical_market_regime"],
      warnings: ["stricter_only_enforcement_display_only_mock"],
      affectedModes: ["NEUTRAL_GRID", "DYNAMIC_NEUTRAL_GRID", "PHASE_2B_ACTIVATION"],
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    regridReadinessBeforeCanonicalGate: {
      status: "NOT_READY",
      score: 40,
      passedGates: ["out_of_grid_context", "old_one_sided_exposure_quarantined"],
      failedGates: ["stable_candles_pending", "cooldown_pending", "candidate_grid_missing"],
      warnings: ["old_buy_exposure_quarantined_not_counted_as_closed_cycle"],
      nextAction: "wait_for_stability_cooldown_and_candidate_grid",
      operatorReviewRequired: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    regridReadinessAfterCanonicalGate: {
      status: "NOT_READY",
      score: 40,
      passedGates: ["out_of_grid_context", "old_one_sided_exposure_quarantined"],
      failedGates: ["stable_candles_pending", "cooldown_pending", "candidate_grid_missing"],
      warnings: ["old_buy_exposure_quarantined_not_counted_as_closed_cycle"],
      nextAction: "wait_for_stability_cooldown_and_candidate_grid",
      operatorReviewRequired: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    canonicalRegimeGateShadowCompare: {
      changed: false,
      downgradeReason: "mock_already_not_ready",
    },
    canonicalRegimeGateEnforcement: {
      enabled: true,
      mode: "STRICTER_ONLY",
      activeReadinessSource: "regridReadinessAfterCanonicalGate",
      beforeStatus: "NOT_READY",
      afterStatus: "NOT_READY",
      changed: false,
      downgradeReason: "mock_already_not_ready",
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    trendZoneCandidate: {
      buildStatus: "NOT_TREND",
      dir: null,
      pullbackZone: null,
      invalidation: null,
      triggerRule: null,
      targets: { t1: null, t2: null },
      entry: { type: null, hint: null },
      smc: { swingHigh1h: null, swingLow1h: null, eq1h: null, liquidityNote: null },
      warnings: ["mock_data_not_runtime_evidence"],
      shadowOnly: true,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    trendStrategy: {
      enabled: false,
      phase: "T-1_SHADOW",
      status: "NO_TRADE",
      direction: null,
      setupReason: "mock_data_not_runtime_evidence",
      entryZone: null,
      currentPrice: null,
      distanceToEntryZonePct: null,
      invalidation: null,
      target1: null,
      target2: null,
      rewardRisk: null,
      confirmationRequired: false,
      confirmationStatus: "NOT_REQUIRED",
      riskStatus: "PASS",
      oldExposurePolicy: "QUARANTINE_OLD_GRID_EXPOSURE",
      countTowardGridClosedCycles: false,
      countTowardTrendEvidence: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      shadowOnly: true,
      reasons: ["mock_data_not_runtime_evidence"],
      warnings: ["trend_strategy_shadow_only_no_execution"],
    },
    trendPaperEpoch: {
      epochId: "trend-shadow:NONE:NO_TRADE",
      source: "TREND_STRATEGY",
      phase: "T-1_SHADOW",
      status: "NO_TRADE",
      direction: null,
      oldGridExposurePolicy: "QUARANTINE_OLD_GRID_EXPOSURE",
      countTowardGridClosedCycles: false,
      countTowardTrendEvidence: false,
    },
    trendTransitionMonitor: {
      status: "IDLE_NO_TRADE",
      severity: "info",
      message: "ข้อมูลจำลอง: ยังไม่มี trend setup",
      operatorAction: "รอ pullback ใหม่ ห้ามไล่ราคา",
      shouldNotifyOperator: false,
      checkedAt: null,
      watchedFields: {
        trendStatus: "NO_TRADE",
        riskStatus: "NO_TRADE_NEAR_TARGET",
        direction: null,
        currentPrice: null,
        entryZone: null,
        invalidation: null,
        target1: null,
        rewardRisk: null,
      },
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    trendManualPaperArmGate: {
      phase: "T-2_DESIGN",
      status: "NOT_READY",
      requiredConditions: ["trend_status_awaiting_or_setup_ready", "risk_status_pass", "zone_build_ready"],
      passedConditions: [],
      failedConditions: ["trend_status_awaiting_or_setup_ready"],
      operatorActionRequired: false,
      setupId: null,
      expiryAt: null,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      notes: ["ข้อมูลจำลอง: ยังไม่พร้อม arm"],
    },
    trendPaperExecutionPreflight: {
      phase: "T-3_PREFLIGHT",
      status: "NOT_READY",
      requiredInputs: ["trend_status_awaiting_or_setup_ready", "risk_status_pass", "zone_build_ready"],
      passedInputs: [],
      failedInputs: ["trend_status_awaiting_or_setup_ready"],
      setupId: null,
      direction: null,
      entry: null,
      stopLoss: null,
      takeProfit1: null,
      takeProfit2: null,
      rewardRisk: null,
      paperArmAllowed: false,
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      journalWriteAllowed: false,
      simulatedFillAllowed: false,
      notes: ["ข้อมูลจำลอง: preflight ยังไม่พร้อม"],
    },
    trendPaperExecutionEngine: {
      enabled: false,
      mode: "PAPER_SIMULATION_ONLY",
      lastAction: "NO_ACTION",
      lastReason: "CONFIG_DISABLED",
      openTrendPaperPosition: null,
      lastEntryAt: null,
      lastExitAt: null,
      trendPaperClosedTrades: 0,
      winRate: null,
      netExpectancyAfterCosts: null,
      paperOnly: true,
      liveActivationAllowed: false,
      exchangeOrderAllowed: false,
    },
    trendPaperArmSession: {
      present: false,
      status: "MISSING",
      sessionId: null,
      direction: null,
      symbol: null,
      startedAt: null,
      expiresAt: null,
      timeRemainingMs: null,
      maxEntries: null,
      usedEntries: null,
      remainingEntries: null,
      maxRiskPerTradePct: null,
      maxSessionRiskPct: null,
      active: false,
      paperOnly: true,
      liveActivationAllowed: false,
      exchangeOrderAllowed: false,
    },
    trendPaperArmIntentBridge: {
      rawStatus: "READY_FOR_OPERATOR_REVIEW",
      effectiveStatus: "READY_FOR_OPERATOR_REVIEW",
      source: "SESSION_MISSING",
      upgradedToArmed: false,
      paperArmIntentRequested: false,
      reasons: ["ข้อมูลจำลอง: ไม่มี session arm intent"],
      paperActivationAllowed: false,
      liveActivationAllowed: false,
    },
    trendEdgeReview: {
      phase: "T-4_EDGE_REVIEW",
      status: "INSUFFICIENT_DATA",
      trendClosedTrades: 0,
      sampleTier: "none",
      winRate: null,
      averageWinR: null,
      averageLossR: null,
      expectancyR: null,
      netExpectancyAfterCosts: null,
      profitFactor: null,
      maxDrawdownR: null,
      maxConsecutiveLosses: null,
      riskOfRuinEstimate: null,
      costDrag: null,
      slippageAttribution: null,
      fundingAttribution: null,
      decision: "HOLD",
      paperActivationAllowed: false,
      liveActivationAllowed: false,
      notes: ["ข้อมูลจำลอง: ยังไม่มี closed trend trade"],
    },
    regimeEvidence: {
      evidenceCompleteness: {
        status: "partial",
        scorePct: 60,
        availableCount: 3,
        expectedCount: 5,
      },
      sourceFreshness: {
        latestDecisionAt: null,
        marketSnapshotAt: null,
        planStatusStateAt: null,
        warnings: [],
      },
      decision: {
        marketMode: "GRID_NEUTRAL",
        regime: "RANGE",
        trendDir: null,
        trendTriggerRule: null,
        trendInvalidation: null,
        smcBias: null,
        structureState: null,
        bos: null,
        choch: null,
        mss: null,
        sweep: null,
        obContext: null,
        fvgContext: null,
      },
      indicators: {
        adx: { value: null, source: "missing" },
        plusDI: { value: null, source: "missing" },
        minusDI: { value: null, source: "missing" },
        rsi: { value: null, source: "missing" },
        atr: { value: null, source: "missing" },
        atrPct: { value: null, source: "missing" },
        bbw: { value: null, source: "missing" },
        macd: { value: null, source: "missing" },
        macdSignal: { value: null, source: "missing" },
        macdHistogram: { value: null, source: "missing" },
        emaSlope: { value: null, source: "missing" },
      },
      indicatorEvidence: {
        source: "market_snapshot",
        calculatedAt: null,
        candleCount: 0,
        timeframe: "15m",
        freshness: {
          latestCandleAt: null,
          ageMs: null,
        },
        missingFields: ["adx", "plusDI", "minusDI", "rsi", "macd"],
        notes: ["insufficient_candles"],
      },
      derivatives: {
        oiBias: null,
        oiChange: null,
        fundingRate: null,
        fundingBias: null,
        fundingRisk: null,
        openInterest: null,
        derivativesBias: null,
      },
      obGate: {
        status: null,
        reason: null,
        score: null,
        passed: null,
        blockedReason: null,
      },
      missingFields: ["indicators.adx", "indicators.plusDI", "indicators.minusDI", "indicators.rsi"],
      availableFields: ["decision.marketMode", "decision.regime"],
      notes: ["indicator_not_available_in_runtime_source"],
    },
    dynamicRegrid: {
      marketMode: "GRID_NEUTRAL",
      regime: "RANGE",
      priceVsGrid: "BELOW_GRID",
      paperLoopState: "REGRID_REQUIRED",
      lastNoTradeReason: "price_below_grid_lower",
      currentPrice: null,
      gridLower: null,
      gridUpper: null,
      gridMid: null,
      buyFillCount: 14,
      sellFillCount: 0,
      closedCycles: 0,
      candidate: {
        candidateStatus: "NO_TRADE",
        candidateReason: "Phase 1 read-only evaluator; activation blocked",
        cooldownRemaining: 4,
        stableCandleCount: 0,
        activationAllowed: false,
      },
    },
  },
  topHud: {
    marketMood: "UNKNOWN",
    simEquity: null,
    dailyPnl: null,
    riskHeat: "UNKNOWN",
    agentsActive: 2,
  },
  bottomLog: [
    { ts: "—", type: "SYSTEM", text: "TradingAgentHQ ตัวอย่าง (ข้อมูลจำลอง — ไม่ใช่ของจริง)" },
    { ts: "—", type: "FILL_RESULT", text: "บันทึก paper MARKET fill (จำลอง)", agentId: "grid_bot" },
    { ts: "—", type: "DECISION", text: "รอประเมิน regime (จำลอง)", agentId: "market_regime" },
    { ts: "—", type: "ALERT", text: "รอบปิดครบ = 0 → ยังไม่มีข้อมูลรอบปิด (honest)", agentId: "risk_manager" },
  ],
  agents: {
    grid_bot: {
      id: "grid_bot", status: "running", visualStates: ["running", "balancing_orders"],
      animation: "grid_working", bubble: "กำลังจัดสมดุลคำสั่ง… (จำลอง)",
      currentTask: "รอบ Paper grid", lastAction: "paper MARKET fill (จำลอง)",
      metric: "fills: 30", confidence: "n/a (paper)",
    },
    trend_bot: {
      id: "trend_bot", status: "unknown", visualStates: ["idle"],
      animation: "idle", bubble: "รอข้อมูล (จำลอง)",
      currentTask: "สแกนโมเมนตัม", lastAction: "—", metric: null, confidence: null,
    },
    risk_manager: {
      id: "risk_manager", status: "guarding", visualStates: ["calm"],
      animation: "idle", bubble: "เฝ้าระวังเงินทุน (จำลอง)",
      currentTask: "เฝ้าความเสี่ยง", lastAction: "ตรวจ flag", metric: "เงินจริง: ปิด", confidence: "safe-mode",
    },
    news_analyst: {
      id: "news_analyst", status: "unknown", visualStates: ["idle"],
      animation: "idle", bubble: "ไม่มีฟีดข่าว (จำลอง)",
      currentTask: "สแกนข่าว", lastAction: "—", metric: null, confidence: null,
    },
    market_regime: {
      id: "market_regime", status: "scanning", visualStates: ["thinking"],
      animation: "idle", bubble: "กำลังอ่าน regime… (จำลอง)",
      currentTask: "จำแนก regime", lastAction: "รอ decision", metric: "mode: UNKNOWN", confidence: null,
    },
    memory_brain: {
      id: "memory_brain", status: "logging", visualStates: ["idle"],
      animation: "idle", bubble: "กำลังบันทึก journal (จำลอง)",
      currentTask: "บันทึกตรวจสอบ (audit log)", lastAction: "เพิ่มเหตุการณ์", metric: null, confidence: null,
    },
  },
};
